#ifndef DEF_OCULUS_H
#define DEF_OCULUS_H

enum Data
{
    DATA_DRAKOS_EVENT,
    DATA_VAROS_EVENT,
    DATA_UROM_EVENT,
    DATA_EREGOS_EVENT,
	DATA_UROM_PLATAFORM

};

enum Data64
{
    DATA_DRAKOS,
    DATA_VAROS,
    DATA_UROM,
    DATA_EREGOS,
	DATA_DRAKOS_TIMER,
	DATA_VAROS_TIMER,
	DARA_UROM_TIMER,
	DATA_EREGOS_TIMER
};

enum Bosses
{
    CREATURE_DRAKOS        = 27654,
    CREATURE_VAROS         = 27447,
    CREATURE_UROM          = 27655,
    CREATURE_EREGOS        = 27656
};

#endif
